[package]
name = "qamd"
version = "0.1.0"
authors = ["Myles Offord <moffor@essex.ac.uk>"]

[dependencies]
toml = "0.4.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
pkg-config = "0.3.11"
bindgen = "0.26.3"

