[variable_config]
odd_characters = { setting = ["!", "#", "  ", "@", "ë", "ç", "ô", "ü"], level = "Warn" }
missing_variable_labels = { setting = true, level = "Warn" }

[value_config]
odd_characters = { setting = ["!", "#", "  ", "@", "ë", "ç", "ô", "ü"], level = "Warn" }
system_missing_value_threshold = { setting = 25, level = "Fail" }

