
# Variable Configuration

[variable_config.odd_characters]
setting = ["!", "#", "  ", "@", "ë", "ç", "ô", "ü"]
desc = "Variable names and lables cannot contain certain 'odd' characters."

[variable_config.missing_variable_labels]
setting = true
desc = "Variables should have a label."

[variable_config.label_max_length]
setting = 79
desc = "Variable labels cannot exceed a max length"

[variable_config.date_format]
setting = [
            # stata date
            "JJJ",     # Day within year (001 - 366)
            "jjj",     # Day within year (1 - 366)
            "DD",      # Day within month (01 - 31)
            "dd",      # Day within month (1 - 31)
            "DAYNAME", # Day of week        Sunday, Monday, ... (aligned)
            "Dayname", # Day of week        Sunday, Monday, ... (unaligned)
            "Day",     # Day of week        Sun, Mon, ...
            "Da",      # Day of week        Su, Mo, ...
            "day",     # Day of week        sun, mon, ...
            "da",      # Day of week        su, mo, ...
            # stata time
            "HH",      # hour               00 - 23
            "Hh",      # hour               00 - 12
            "hH",      # hour               0 - 23
            "hh",      # hour               0 - 12
            "MM",      # minute             00 - 59
            "mm",      # minute             0 - 59
            "SS",      # second             00 - 60 (sic, due to leap seconds)
            "ss",      # second             0 - 60 (sic, due to leap seconds)
            ".s",      # tenths             .0 - .9
            ".ss",     # hundredths         .00 - .99
            ".sss",    # thousandths        .000 - .999
            "YY",
            "yy",
            # SPSS
            "SDATE",
            "TIME"
]
desc = "Flags date formats that are too specific and could potentially be disclosive."

[variable_config.primary_variable]
setting = "id"
desc = "Groups the variables"

[variable_config.variables_with_unique_values]
setting = 1
desc = "Detects values as outliers if they unique."

## Value Configuration

[value_config.odd_characters]
setting = ["!", "#", "  ", "@", "ë", "ç", "ô", "ü"]
desc = "Values & value labels shouldn't contain certain 'odd' characters."

[value_config.label_max_length]
setting = 39
desc = "Value labels cannot exceed a maximum length"

[value_config.system_missing_value_threshold]
setting = 25
desc = "Variables with large quantities of values missing."

[value_config.defined_missing_no_label]
setting = true
desc = "Values defined as missing must have a label. This only affects SPSS files."

