---
# metadata_only: ~
# progress: ~

spellcheck:
  setting:
    - '/usr/share/dict/words'
    - 'C:\path\to\dictonary\file.txt'
  desc: ""

## Basic File Checks

# Checking whether the file name contains illegal and/or odd characters
bad_filename:
  setting: '^([a-zA-Z0-9]+)\.([a-zA-Z0-9]+)$'
  desc: ""

variable_config:
  odd_characters:
    setting:
      - "!"
      - "#"
      - "  "
      - "@"
      - ë
      - ç
      - ô
      - ü
    desc: ""

  missing_variable_labels:
    setting: true
    desc: ""

  label_max_length:
    setting: 79
    desc: ""

  # date_format: ~

  primary_variable:
    setting: Caseno
    desc: ""

  variables_with_unique_values:
    setting: 1
    desc: ""

value_config:
  odd_characters:
    setting:
      - "!"
      - "#"
      - "  "
      - "@"
      - ë
      - ç
      - ô
      - ü
    desc: ""

  system_missing_value_threshold:
    setting: 25
    desc: ""

  label_max_length:
    setting: 39
    desc: ""

  defined_missing_no_label:
    setting: true
    desc: ""

  # regex_patterns:
  #   setting:
  #     # Simple Email address Regex
  #     - "^([\\w\\.\\-]+)@([\\w\\-]+)((\\.(\\w){2,4})+)$"
  #     # UK post code regex
  #     - "([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9]?[A-Za-z]))))\\s?[0-9][A-Za-z]{2})",
  #     # Email addresses as per RFC 2822
  #     - "((([a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(\\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*)|(\"(([\\x01-\\x08\\x0B\\x0C\\x0E-\\x1F\\x7F]|[\\x21\\x23-\\x5B\\x5D-\\x7E])|(\\[\\x01-\\x09\\x0B\\x0C\\x0E-\\x7F]))*\"))@(([a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(\\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*)|(\\[(([\\x01-\\x08\\x0B\\x0C\\x0E-\\x1F\\x7F]|[\\x21-\\x5A\\x5E-\\x7E])|(\\[\\x01-\\x09\\x0B\\x0C\\x0E-\\x7F]))*\\])))"
  #   desc: ""

  duplicate_values:
    setting:
      - Caseno
    desc: ""

